name: CI

on: push

jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    env:
      FC: gfortran
      GCC_V: 11

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt install -y gfortran-${GCC_V} cmake mpich
        sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-${GCC_V} 100

    - name: Build and Test
      run: |
        mkdir build
        cmake -S . -B build -Wdev -DCMAKE_INSTALL_PREFIX:PATH="${HOME}/OpenCoarrays" -DCMAKE_BUILD_TYPE:STRING="Debug" ..
        cmake --build build -j $(nproc)
        cmake --build build -t install -j $(nproc) || echo "installation failed"
        ctest --output-on-failure --schedule-random --repeat-until-fail 1 --timeout 200
        make install
        make uninstall
